### ISSUE TITLE
File transfers to master are slow

### ISSUE THREAD

**Issue by mmuetzel** [gnu-octave/octave-buildbot#5]
The files are currently transferred using buildbot's MultipleFileUpload function. Reading some reports about it, it is known to be slow.
I don't really have a solution here. I can only try to throw in some ideas.
Are you able to connect from the workers to the master via ssh?
If you can, something like this might be faster:
rsync -a -e ssh LOCALFILE user@master:REMOTEFILE

**Comment by siko1056** [comment]
Thanks for your ideas, this is indeed something I am struggling with too and also [read some of the reports](https://github.com/buildbot/buildbot/issues?q=is%3Aissue+upload), but did not find the "killer" solution yet.

I am thinking about using `rsync` or `scp` uploads, too.  So far I did not look deeper into this, because I lack of knowledge how to remotely create such a connection inside a Docker container to store the data inside a Docker volume :innocent:

**Comment by mmuetzel** [comment]
I probably won't be of much help. From my point of you, you are the docker expert. :-)
Could one of these be useful?
https://hub.docker.com/r/instrumentisto/rsync-ssh/
https://github.com/ome/rsync-ssh-docker

**Comment by siko1056** [comment]
Thanks for the links :+1:   Yes maybe some solution like this might come into play.  As a first step, I want to make an experiment how fast a rsync transfer of a file can be in theory.

**Comment by siko1056** [comment]
Fixed by using `rync`.

https://siko1056.github.io/blog/2020/11/08/octave-buildbot-boosted.html
